CREATE DATABASE BCA_MUSCUTIME

CREATE TABLE PROGRAMME (
ID int IDENTITY(1,1),
NOM varchar(38),
DUREE float,
DESCRIPTION text,
AUTEUR varchar(38),
IFSTATS char(3),
CONSTRAINT PK_PROGRAMME_ID PRIMARY KEY (ID)
)

CREATE TABLE EXERCICE (
ID int IDENTITY(1,1),
NOM varchar(38),
DUREE float,
DESCRIPTION text,
CONSTRAINT PK_EXERCICE_ID PRIMARY KEY (ID)
)

CREATE TABLE POSSEDE (
IDPRO int,
IDEXERCICE1 int,
IDEXERCICE2 int,
IDEXERCICE3 int,
IDEXERCICE4 int,
IDEXERCICE5 int,
CONSTRAINT PK_POSSEDE_IDPRO PRIMARY KEY (IDPRO),
CONSTRAINT FK_POSSEDE_IDPRO FOREIGN KEY (IDPRO) REFERENCES PROGRAMME (ID),
CONSTRAINT FK_POSSEDE_IDEXERCICE1 FOREIGN KEY (IDEXERCICE1) REFERENCES EXERCICE (ID),
CONSTRAINT FK_POSSEDE_IDEXERCICE2 FOREIGN KEY (IDEXERCICE2) REFERENCES EXERCICE (ID),
CONSTRAINT FK_POSSEDE_IDEXERCICE3 FOREIGN KEY (IDEXERCICE3) REFERENCES EXERCICE (ID),
CONSTRAINT FK_POSSEDE_IDEXERCICE4 FOREIGN KEY (IDEXERCICE4) REFERENCES EXERCICE (ID),
CONSTRAINT FK_POSSEDE_IDEXERCICE5 FOREIGN KEY (IDEXERCICE5) REFERENCES EXERCICE (ID),
)
INSERT INTO EXERCICE (NOM,DUREE,DESCRIPTION) VALUES ('Course',60,'Courir pendant 1 heure')
INSERT INTO EXERCICE (NOM,DUREE,DESCRIPTION) VALUES ('Développé Couché',20,'Soulever une barre avec des poids')
INSERT INTO EXERCICE (NOM,DUREE,DESCRIPTION) VALUES ('Pompes',10,'Faire des pompes sur le sol, 10 minutes = 200 pompes')
INSERT INTO EXERCICE (NOM,DUREE,DESCRIPTION) VALUES ('Squats',10,'Fléchir ses jambes de haut en bas en gardant les bras bien tendu.')
INSERT INTO EXERCICE (NOM,DUREE,DESCRIPTION) VALUES ('Traction',20,'S''accrocher a une barre et soulever son corps')
SELECT * FROM PROGRAMME
SELECT * FROM EXERCICE
SELECT * FROM POSSEDE